[profile.default]
src = "src"
out = "build"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
#solc_version = "0.5.17"
optimizer = true
optimizer_runs = 200
